version: "3.7"
services:
  php-apache:
    build: "docker/php-apache/"
    container_name: "api-php-apache"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    restart: always
    ports:
      - "8080:80"
  mysql:
    image: mysql:5.7
    container_name: "api-mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "directus"
#    volumes:
#      - ./volumes/mysql:/var/lib/mysql
    restart: always
    ports:
      - "8806:3306"
